name: domof
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^16.0.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.3
  get_it: ^8.0.3
  dio: ^5.8.0+1
  flutter_svg: ^2.2.0
  json_annotation: ^4.9.0
  http: ^1.4.0
  retrofit: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  retrofit_generator: ^9.7.0
  build_runner: ^2.5.4
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: SFPro-Light
      fonts:
        - asset: assets/fonts/SFProText-Light.ttf
    - family: SFPro-Medium
      fonts:
        - asset: assets/fonts/SFProText-Medium.ttf
    - family: SFPro-SemiBold
      fonts:
        - asset: assets/fonts/SFProText-Semibold.ttf
    - family: SFPro-Bold
      fonts:
        - asset: assets/fonts/SFProText-Bold.ttf
    - family: SFPro-Regular
      fonts:
        - asset: assets/fonts/SFProText-Regular.ttf
